### ISSUE TITLE
How can I build this?

### ISSUE THREAD

**Issue by ahmad-luqman** [zeeshanejaz/SmartHomeSDK#1]
Its not clear how to build this. 
So on windows how do you build it. Are you using cygwin?
On linux the make file seems incompatible:
First I got the following build error:

```
$ make
 CXX src/Socket.cpp
 CXX src/Utility.cpp
 CXX src/EnumParser.cpp
 CXX src/ProtocolPacket.cpp
 CXX src/CommClient.cpp
src/CommClient.cpp: In member function ‘ProtocolPacket* CommClient::GetResponse(ProtocolPacket*)’:
src/CommClient.cpp:74:24: error: ‘gettimeofday’ was not declared in this scope
  gettimeofday(&tp, NULL); 
                        ^
Makefile:30: recipe for target 'build/CommClient.o' failed
make: *** [build/CommClient.o] Error 1
```

I fixed that by adding #include <sys/time.h> in CommClient.h.
Than I got he following error:

```
$ make
 CXX src/CommClient.cpp
 CXX src/ProtocolManager.cpp
 CXX src/ModelController.cpp
 CXX src/SmartHomeSDK.cpp
 Linking...
g++: error: unrecognized command line option ‘-Wl’
Makefile:25: recipe for target 'release/SmartHomeSDK.dll' failed
make: *** [release/SmartHomeSDK.dll] Error 1

```

I am seeing .dll as an output so it seems to be more windows specific.
# Suggestions:
- Use cross-platform tool like cmake and fix build errors.
- Have a CI build, use https://travis-ci.org/

**Comment by zeeshanejaz** [comment]
Thanks for finding this. I have now fixed the issues with makefile and updated the README file. I am using Windows 10's Ubuntu Shell for compilation. Give it another go :)

Yes, CI and creating Releases is the next step. Contribution is welcomed.
